name: build

on:
  push:
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  build-swift:
    strategy:
      fail-fast: false
      matrix:
        swift: ['swift5.10', 'swift5-newer-compiler', 'swift6']
        include:
          - swift: 'swift5.10'
            language-mode: '5'
            xcode-path: '/Applications/Xcode_15.4.app'
            macos: 'macos-14'
          - swift: 'swift5-newer-compiler'
            language-mode: '5'
            xcode-path: '/Applications/Xcode_16.2.app'
            macos: 'macos-14'
          - swift: 'swift6'
            language-mode: '6'
            xcode-path: '/Applications/Xcode_16.2.app'
            macos: 'macos-14'
    
    env:
      DEVELOPER_DIR: ${{ matrix.xcode-path }}

    runs-on: ${{ matrix.macos }}
    timeout-minutes: 15

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: swift version
      run: swift --version

    - name: build with complete concurrency checking
      run: >
        swift build
        --target OAuth2
        -Xswiftc -swift-version
        -Xswiftc '${{ matrix.language-mode }}'
        -Xswiftc -warnings-as-errors

    - name: run unit tests
      run: >
        xcodebuild
        -workspace '.swiftpm/xcode/package.xcworkspace'
        -scheme OAuth2
        -configuration Debug
        -destination 'platform=macOS'
        SWIFT_VERSION='${{ matrix.language-mode }}'
        SWIFT_TREAT_WARNINGS_AS_ERRORS=YES
        test

  build-xcode:
    name: 'build-xcode (${{ matrix.platform }})'

    strategy:
      fail-fast: false
      matrix:
        macos: [ 'macos-14' ]
        platform: [ 'macOS', 'iOS', 'tvOS', 'watchOS' ]
    
    env:
      DEVELOPER_DIR: '/Applications/Xcode_15.4.app'

    runs-on: ${{ matrix.macos }}

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: xcode version
      run: xcodebuild -version

    - name: swift version
      run: swift --version

    - name: build
      run: >
        xcodebuild
        -workspace '.swiftpm/xcode/package.xcworkspace'
        -scheme OAuth2
        -configuration Debug
        -destination 'generic/platform=${{ matrix.platform }}'
        -showBuildTimingSummary
        build
